[database]
path = "./tmp/ytx.db"
max_open_conns = 10
max_idle_conns = 5

[server]
host = "localhost"
port = 3000

[credentials.spotify]
client_id = "your_spotify_client_id"
client_secret = "your_spotify_client_secret"
redirect_uri = "http://localhost:8080/callback"

[credentials.youtube]
api_key = ""
proxy_url = "http://localhost:8080"
headers_path = "~/.config/ytx/headers_auth.json"
